Auction_Website/urls.py
from django.urls import path
from . import views

app_name = 'auction'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.activate,
         name='activate'),
    path('<int:item_id>/', views.item_details, name='item_details'),
    path('profile_page/', views.profile_page, name='profile_page'),
    path('favorite/<item_id>/', views.favorites, name='favorite'),
    path('favorites/', views.favorites_page, name='favorites'),
    path('add_bid/<int:item_id>', views.add_bid, name='add_bid'),
    path('winners/', views.winners, name='winners'),
    path('bids/', views.bids_page, name='bids_page'),

]

Auction_Website/templates/auction/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'auction:activate' uidb64=uid token=token %}
{% endautoescape %}

Auction_Website/templates/auction/account_activation_invalid.html
{% extends 'auction/base.html' %}

{% block content %}
<p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

Auction_Website/templates/auction/account_activation_sent.html
{% load static %}
{% extends 'base.html' %}

{% block content %}
<p>Please confirm your email address to complete the registration. </p>
{% endblock %}

Auction_Website/templates/auction/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'auction/style.css' %}"/>
    <title>{% block title %}Hashira Auction{% endblock %}</title>
</head>
<body>
    <!-- Top Navigation Menu -->
    <div class="topnav">
        <a href="" class="active">Hashira Auction</a>
        <div id="myLinks">
            <a href="{% url 'auction:index' %}" class="item_menu">Home</a>
            <a href="{% url 'auction:profile_page' %}" class="item_menu">Profile</a>
            <a href="{% url 'auction:favorites' %}" class="item_menu">Favorites</a>
            <a href="{% url 'auction:bids_page' %}" class="item_menu">Your Bids List</a>
            <a href="{% url 'admin:auction_item_changelist' %}" class="item_menu">Edit/Add items for Auction</a>
            <a href="{% url 'logout' %}">logout</a>
            <a href="" class="item_menu">Your Current Balance: ${{ balance }}</a>
        </div>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <img src="{% static 'auction/images/hamburger.png' %}" style="width: 25px;height: 25px;">
        </a>
    </div>
    
    <script>
        function myFunction() {
            var x = document.getElementById("myLinks");
            if (x.style.display === "block") {
                x.style.display = "none";
            } else {
                x.style.display = "block";
            }
        }
    </script>
<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

Auction_Website/templates/auction/bids_page.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}Bids{% endblock %}

{% block content %}
<div>
    <h1>List of Items you have bid on.</h1>
</div>
{% for item in items_bid_on %}
<div class="item_wrapper">
    <div class="gallary_image_div">
        <a href="{% url 'auction:item_details' item.id %}">
            <img class="gallary_image" src="{{ item.image.url }}">
        </a>
    </div>
    <h2>{{ item.item_name }}</h2>

</div>
{% empty %}
<div>
    <h2>
        No bids yet, take a look at the item gallery first.
    </h2>
</div>
{% endfor %}

<br style="clear: left;">
    <h1 style="padding-top: 10mm;">Items you are currently winning:</h1>
</br>
{% for b in bids %}
    <div class="item_wrapper">
        <div class="gallary_image_div">
            <a href="{% url 'auction:item_details' b.id %}">
                <img class="gallary_image" src="{{ b.image.url }}">
            </a>
        </div>
        <h2>{{ b.item_name }}</h2>
    </div>
{% endfor %}

{% endblock %}

Auction_Website/templates/auction/favorites.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}Favorites{% endblock %}

{% block content %}
<div>
    <h1>Your list of favorite items</h1>
</div>
{% for item in favorite_items %}
<div class="item_wrapper">
    <div class="gallary_image_div">
        <a href="{% url 'auction:item_details' item.id %}">
            <img class="gallary_image" src="{{ item.image.url }}">
        </a>

    </div>
    <h2>{{ item.item_name }}</h2>

</div>
{% empty %}
<div>
    <h2>
        No favorite items yet take a look at the item gallery first.
    </h2>
</div>
{% endfor %}

{% endblock %}

Auction_Website/templates/auction/gallery.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}Item Gallery{% endblock %}

{% block content %}
{% if user.is_authenticated %}

    <body>
		{% for i in item %}
        {% if i.is_silent_item == True %}
		<div class="item_wrapper">
            <div class="gallary_image_div">
                <a href="{% url 'auction:item_details' i.id %}">
                    <img class="gallary_image" src="{{ i.image.url }}">
                </a>
            </div>
            <h2>{{ i.item_name }}</h2> <!-- needs a link still -->
        </div>
        {% endif %}
		{% endfor %}
    </body>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

Auction_Website/templates/auction/home.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
<p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

Auction_Website/templates/auction/item_details.html
{% extends 'auction/base.html' %}
{% block content %}
{% load custom_tags %}
<header>
    <h1>
      Item Details
    </h1>
</header>
<div id="middle">
    <div class="gallary_image_div">
        <img class="gallary_image" src="{{ item.image.url }}">
    </div>
    <h2>
      {{ item.item_name }}
    </h2>
    
    <p>
        {{ item.description }}
    </p>
    <h2>
    Current Highest Bid
    </h2>
    <h3>
        ${{ bid }}
    </h3>
</div>
<div id="form">
    <h3>
        Make a Bid
    </h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'auction:add_bid' item.id %}" method="post">
        {% csrf_token %}
        <label for="Bid">Bid Amount:
            <input type="number" name="bid" id="bid"><br>
        </label><br>
        <div>
            <button id="submission" type="submit"style="margin-top: 20px;">Submit</button>
        </div>
    </form>
    <div id="favorite-section">
        {% if is_favorite %}
        <button type="button" class="btn btn-outline-primary watch_button" onclick="location.href='/favorite/{{item.id}}'">
            Un-Favorite
        </button>
        {% else %}
        <button type="button" class="btn btn-outline-primary watch_button" onclick="location.href='/favorite/{{item.id}}'">
            Favorite
        </button>
        {% endif %}
    </div>
</div>
{% endblock %}

Auction_Website/templates/auction/profile_page.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!

Your id number is {{user.id}}

<div>First Name: {{ user.first_name }}</div>
<div>Last Name: {{ user.last_name }}</div>
<div>email: {{ user.email }}</div>

<p><a href="{% url 'logout' %}">logout</a></p>
<p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

Auction_Website/templates/auction/signup.html
{% extends 'auction/base.html' %}
{% load static %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Create Account</button>
</form>
{% endblock %}

Auction_Website/templates/auction/winners.html
{% extends 'auction/base.html' %}
{% load static %}

{% block title %}The Winners!{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div>Hi {{ user.username }}! Did you Win?: </div>
<p><a href="{% url 'logout' %}">logout</a></p>
<p><a href="{% url 'password_reset' %}">reset password</a></p>

<h1>List of Winners:</h1>
<br>
{% for w in winner %}
<div class="item_wrapper">
    <h2>{{ w.user.username }}</h2>
    <div class="gallary_image_div">
        <p> {{w.item_won.item_name}}</p>
        <img class="gallary_image" src="{{ w.item_won.image.url }}">
    </div>
</div>
{% endfor %}
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}